// apps/frontend/src/App.svelte
<script lang="ts">
  import { onMount, onDestroy, untrack } from 'svelte';
  import { Play, RefreshCw, X, XCircle, Trash2 } from 'lucide-svelte';
  import MonacoEditor from './MonacoEditor.svelte';
  import TaskRow from './TaskRow.svelte';
  import TaskDialog from './TaskDialog.svelte';
  import Button from '$lib/components/ui/button.svelte';
  import Dialog from '$lib/components/ui/dialog.svelte';

  interface Task {
    id: string;
    generateName: string;
    phase: string;
    startedAt: string;
    finishedAt: string;
    createdAt: string;
    pythonCode: string;
    message?: string;
  }

  interface LogEntry {
    node: string;
    pod: string;
    phase: string;
    logs: string;
  }

  const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:8000';

  // Convert to $state runes
  let tasks = $state<Task[]>([]);
  let initialLoading = $state(true);
  let selectedTaskId = $state<string | null>(null);
  let activeTab = $state<'code' | 'logs'>('code');
  
  // Track previous values to detect actual changes
  let prevSelectedTaskId: string | null = null;
  let prevActiveTab: 'code' | 'logs' = 'code';
  let taskLogs = $state<LogEntry[]>([]);
  let loadingLogs = $state(false);
  let showSubmitModal = $state(false);
  const defaultPythonCode = "print('Processing task in Kind...')";
  let pythonCode = $state(defaultPythonCode);
  let submitting = $state(false);

  // Reset pythonCode when dialog closes
  $effect(() => {
    if (!showSubmitModal) {
      pythonCode = defaultPythonCode;
    }
  });

  let ws: WebSocket | null = null;
  let reconnectTimeout: ReturnType<typeof setTimeout> | null = null;
  let reconnectAttempts = 0;
  const maxReconnectAttempts = 5;
  let lastLogsHash = '';
  let taskRefreshInterval: ReturnType<typeof setInterval> | null = null;
  const TASK_REFRESH_INTERVAL_MS = 5000; // 5 seconds
  let currentWebSocketTaskId: string | null = null;
  
  // Track the last connected task/tab to prevent unnecessary reconnections
  let lastConnectedTaskId: string | null = null;
  let lastConnectedTab: 'code' | 'logs' | null = null;
  
  // Track which completed tasks have already had their final logs fetched
  let completedTasksWithLogsFetched = $state<Set<string>>(new Set());
  
  // Manual subscription pattern - only update when values actually change
  // This avoids the reactive effect system causing unnecessary re-runs

  // Convert reactive statement to $derived
  let selectedTask = $derived(selectedTaskId ? tasks.find(t => t.id === selectedTaskId) || null : null);

  function getPhaseColor(phase: string): string {
    switch (phase) {
      case 'Succeeded': return '#10b981';
      case 'Failed': return '#ef4444';
      case 'Running': return '#3b82f6';
      case 'Pending': return '#f59e0b';
      default: return '#6b7280';
    }
  }

  function tasksChanged(oldTasks: Task[], newTasks: Task[]): boolean {
    if (oldTasks.length !== newTasks.length) return true;
    
    const oldMap = new Map(oldTasks.map(t => [t.id, t]));
    
    for (const newTask of newTasks) {
      const oldTask = oldMap.get(newTask.id);
      if (!oldTask) return true;
      
      if (
        oldTask.phase !== newTask.phase ||
        oldTask.startedAt !== newTask.startedAt ||
        oldTask.finishedAt !== newTask.finishedAt
      ) {
        return true;
      }
    }
    
    return false;
  }

  async function fetchTasks(isInitial = false) {
    try {
      if (isInitial) {
        initialLoading = true;
      }
      const res = await fetch(`${apiUrl}/api/v1/tasks`);
      const data = await res.json();
      const newTasks = data.tasks || [];
      
      if (tasksChanged(tasks, newTasks)) {
        tasks = newTasks;
      }
    } catch (error) {
      console.error('Failed to fetch tasks:', error);
    } finally {
      if (isInitial) {
        initialLoading = false;
      }
    }
  }

  function logsHash(logs: LogEntry[]): string {
    return logs.map(l => `${l.node}:${l.pod}:${l.phase}:${l.logs.length}:${l.logs.slice(-100)}`).join('|');
  }

  function getTotalLogsLength(logs: LogEntry[]): number {
    return logs.reduce((total, log) => total + log.logs.length, 0);
  }

  function hasMoreLogs(oldLogs: LogEntry[], newLogs: LogEntry[]): boolean {
    // Always update if old logs are empty (initial load)
    if (oldLogs.length === 0 && newLogs.length > 0) return true;
    
    // If new logs have more entries, they have more content
    if (newLogs.length > oldLogs.length) return true;
    
    // If same number of entries, check if any log entry has more content
    if (newLogs.length === oldLogs.length) {
      for (let i = 0; i < newLogs.length; i++) {
        const oldLog = oldLogs[i];
        const newLog = newLogs[i];
        
        // If entry doesn't exist in old logs, it's new content
        if (!oldLog) return true;
        
        // If logs content is longer, it has more content
        if (newLog.logs.length > oldLog.logs.length) return true;
        
        // If logs content changed and is longer or equal but different (new content appended)
        if (newLog.logs !== oldLog.logs && newLog.logs.length >= oldLog.logs.length) {
          // Check if new logs contain old logs (content was appended)
          if (newLog.logs.startsWith(oldLog.logs)) return true;
        }
      }
    }
    
    // Check total length as fallback
    const oldTotal = getTotalLogsLength(oldLogs);
    const newTotal = getTotalLogsLength(newLogs);
    return newTotal > oldTotal;
  }

  function disconnectWebSocket() {
    if (ws) {
      ws.close();
      ws = null;
    }
    if (reconnectTimeout) {
      clearTimeout(reconnectTimeout);
      reconnectTimeout = null;
    }
    reconnectAttempts = 0;
    currentWebSocketTaskId = null;
  }

  function connectWebSocket(taskId: string) {
    // Check if task is already completed - don't connect WebSocket for completed tasks
    const task = tasks.find(t => t.id === taskId);
    if (task && (task.phase === 'Succeeded' || task.phase === 'Failed')) {
      console.log('Task is completed, skipping WebSocket connection:', taskId, task.phase);
      // Ensure we've fetched final logs once
      if (!completedTasksWithLogsFetched.has(taskId)) {
        completedTasksWithLogsFetched.add(taskId);
        fetchLogsViaRest(taskId);
      }
      return;
    }
    
    // Don't reconnect if already connected to the same task
    if (ws && ws.readyState === WebSocket.OPEN && currentWebSocketTaskId === taskId) {
      console.log('WebSocket already connected to task:', taskId);
      return;
    }
    
    // Additional check: if we're already in the process of connecting to this task, don't connect again
    if (currentWebSocketTaskId === taskId && ws && (ws.readyState === WebSocket.CONNECTING || ws.readyState === WebSocket.OPEN)) {
      console.log('WebSocket connection already in progress or open for task:', taskId);
      return;
    }
    
    console.log('Connecting WebSocket to task:', taskId);
    lastLogsHash = '';
    disconnectWebSocket();
    currentWebSocketTaskId = taskId;

    const wsUrl = apiUrl.replace(/^http/, 'ws') + `/ws/tasks/${taskId}/logs`;
    
    loadingLogs = true;
    reconnectAttempts = 0;

    try {
      ws = new WebSocket(wsUrl);

      ws.onopen = () => {
        console.log('WebSocket connected for task:', taskId);
        loadingLogs = false;
        reconnectAttempts = 0;
      };

      ws.onmessage = (event) => {
        try {
          const message = JSON.parse(event.data);
          
          // Check if task is completed - stop processing messages for completed tasks
          const task = tasks.find(t => t.id === taskId);
          if (task && (task.phase === 'Succeeded' || task.phase === 'Failed')) {
            console.log('Task completed, closing WebSocket:', taskId, task.phase);
            // Mark as fetched before disconnecting
            if (!completedTasksWithLogsFetched.has(taskId)) {
              completedTasksWithLogsFetched.add(taskId);
            }
            disconnectWebSocket();
            loadingLogs = false;
            return;
          }
          
          if (message.type === 'logs') {
            const newLogs = message.data || [];
            const newHash = logsHash(newLogs);
            
            // Only update if logs have more content than currently displayed
            if (newHash !== lastLogsHash && hasMoreLogs(taskLogs, newLogs)) {
              lastLogsHash = newHash;
              taskLogs = newLogs;
            }
            loadingLogs = false;
          } else if (message.type === 'complete') {
            // Task completed - mark as fetched and disconnect WebSocket
            console.log('Task completed via WebSocket, disconnecting:', taskId);
            completedTasksWithLogsFetched.add(taskId);
            disconnectWebSocket();
            loadingLogs = false;
          } else if (message.type === 'error') {
            console.error('WebSocket error:', message.message);
            if (taskLogs.length === 0) {
              taskLogs = [{
                node: 'error',
                pod: 'N/A',
                phase: 'Error',
                logs: `Error: ${message.message}`
              }];
            }
            loadingLogs = false;
          }
        } catch (error) {
          console.error('Failed to parse WebSocket message:', error);
        }
      };

      ws.onerror = (error) => {
        console.error('WebSocket error:', error);
        loadingLogs = false;
      };

      ws.onclose = (event) => {
        console.log('WebSocket closed:', event.code, event.reason);
        ws = null;
        
        if (event.code !== 1000 && selectedTaskId === taskId && reconnectAttempts < maxReconnectAttempts) {
          reconnectAttempts += 1;
          const delay = Math.min(1000 * Math.pow(2, reconnectAttempts), 10000);
          
          console.log(`Reconnecting in ${delay}ms (attempt ${reconnectAttempts}/${maxReconnectAttempts})...`);
          
          reconnectTimeout = setTimeout(() => {
            connectWebSocket(taskId);
          }, delay);
        } else if (reconnectAttempts >= maxReconnectAttempts) {
          if (taskLogs.length === 0) {
            taskLogs = [{
              node: 'error',
              pod: 'N/A',
              phase: 'Error',
              logs: 'Connection lost. Maximum reconnection attempts reached.'
            }];
          }
          loadingLogs = false;
        }
      };
    } catch (error) {
      console.error('Failed to create WebSocket:', error);
      loadingLogs = false;
      taskLogs = [{
        node: 'error',
        pod: 'N/A',
        phase: 'Error',
        logs: `Failed to connect: ${error instanceof Error ? error.message : 'Unknown error'}`
      }];
    }
  }

  async function fetchLogsViaRest(taskId: string) {
    // Check if task is already completed
    const task = tasks.find(t => t.id === taskId);
    if (task && (task.phase === 'Succeeded' || task.phase === 'Failed')) {
      // For completed tasks, only skip if we've already fetched AND we have logs displayed
      // This allows fetching logs when user opens a completed task for the first time
      if (completedTasksWithLogsFetched.has(taskId) && taskLogs.length > 0) {
        console.log('Task is completed and logs already fetched, skipping:', taskId, task.phase);
        return;
      }
      console.log('Fetching logs for completed task:', taskId, task.phase);
    }
    
    try {
      loadingLogs = true;
      const res = await fetch(`${apiUrl}/api/v1/tasks/${taskId}/logs`);
      if (res.ok) {
        const data = await res.json();
        const logs = data.logs || [];
        // For completed tasks, always update if we got logs (even if same content)
        // For running tasks, only update if logs have more content
        if (logs.length > 0) {
          if (task && (task.phase === 'Succeeded' || task.phase === 'Failed')) {
            // For completed tasks, always show the logs and mark as fetched
            taskLogs = logs;
            completedTasksWithLogsFetched.add(taskId);
          } else if (hasMoreLogs(taskLogs, logs)) {
            // For running tasks, only update if more content
            taskLogs = logs;
          }
        } else if (task && (task.phase === 'Succeeded' || task.phase === 'Failed')) {
          // Even if no logs, mark as fetched to prevent repeated attempts
          completedTasksWithLogsFetched.add(taskId);
        }
      }
    } catch (error) {
      console.error('Failed to fetch logs via REST:', error);
      // Mark as fetched even on error to prevent repeated failed attempts for completed tasks
      if (task && (task.phase === 'Succeeded' || task.phase === 'Failed')) {
        completedTasksWithLogsFetched.add(taskId);
      }
    } finally {
      loadingLogs = false;
    }
  }

  // Manual WebSocket management - separate from reactive system
  // This function only reconnects if the taskId or tab actually changed
  function manageWebSocketConnection(taskId: string | null, tab: 'code' | 'logs') {
    // Check if task is already completed
    if (taskId) {
      const task = tasks.find(t => t.id === taskId);
      if (task && (task.phase === 'Succeeded' || task.phase === 'Failed')) {
        // For completed tasks, fetch logs once when user opens logs tab
        if (tab === 'logs') {
          // Fetch logs if we haven't fetched yet OR if we don't have logs displayed
          // This ensures logs are shown when user opens a completed task
          if (!completedTasksWithLogsFetched.has(taskId) || taskLogs.length === 0) {
            console.log('Task completed, fetching logs:', taskId, task.phase);
            // Fetch logs (will mark as fetched inside fetchLogsViaRest)
            fetchLogsViaRest(taskId);
          }
          // Don't connect WebSocket for completed tasks
          if (lastConnectedTaskId === taskId) {
            disconnectWebSocket();
            lastConnectedTaskId = null;
            lastConnectedTab = null;
          }
          return;
        } else {
          // Not on logs tab - just disconnect if connected
          if (lastConnectedTaskId === taskId) {
            disconnectWebSocket();
            lastConnectedTaskId = null;
            lastConnectedTab = null;
          }
          return;
        }
      }
    }
    
    // Check if values actually changed compared to what we last connected to
    const taskIdChanged = taskId !== lastConnectedTaskId;
    const tabChanged = tab !== lastConnectedTab;
    
    // Early return if values haven't changed - prevents unnecessary reconnections
    if (!taskIdChanged && !tabChanged) {
      return;
    }
    
    // Disconnect any existing connection first
    if (lastConnectedTaskId !== null) {
      disconnectWebSocket();
    }
    
    const shouldConnect = taskId && tab === 'logs';
    
    if (shouldConnect) {
      // Connect to the new task
      lastLogsHash = '';
      fetchLogsViaRest(taskId);
      connectWebSocket(taskId);
      lastConnectedTaskId = taskId;
      lastConnectedTab = tab;
    } else {
      // Not on logs tab or no task selected
      lastConnectedTaskId = null;
      lastConnectedTab = null;
      if (tab !== 'logs') {
        taskLogs = [];
      }
      lastLogsHash = '';
    }
  }
  
  // Remove reactive effect - we'll manage WebSocket connections manually
  // This prevents the reactive system from causing unnecessary reconnections
  // WebSocket management is now triggered explicitly when selectedTaskId or activeTab change

  async function runTask() {
    try {
      submitting = true;
      const res = await fetch(`${apiUrl}/api/v1/tasks/submit`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ pythonCode }),
      });
      
      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.detail || 'Failed to submit task');
      }
      
      const data = await res.json();
      alert('Started Workflow: ' + data.id);
      showSubmitModal = false;
      // pythonCode will be reset by the $effect when showSubmitModal becomes false
      fetchTasks();
    } catch (error) {
      console.error('Failed to submit task:', error);
      alert('Failed to submit task: ' + (error instanceof Error ? error.message : 'Unknown error'));
    } finally {
      submitting = false;
    }
  }

  async function cancelTask(taskId: string) {
    if (!confirm('Are you sure you want to cancel this task?')) {
      return;
    }

    try {
      const res = await fetch(`${apiUrl}/api/v1/tasks/${taskId}`, {
        method: 'DELETE',
      });
      
      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.detail || 'Failed to cancel task');
      }
      
      if (selectedTaskId === taskId) {
        selectedTaskId = null;
        activeTab = 'code';
        taskLogs = [];
        disconnectWebSocket();
      }
      
      fetchTasks();
      alert('Task cancelled successfully');
    } catch (error) {
      console.error('Failed to cancel task:', error);
      alert('Failed to cancel task: ' + (error instanceof Error ? error.message : 'Unknown error'));
    }
  }

  async function deleteTask(taskId: string) {
    if (!confirm('Are you sure you want to delete this task? This will permanently remove the workflow and all its logs from the database.')) {
      return;
    }

    try {
      const res = await fetch(`${apiUrl}/api/v1/tasks/${taskId}/delete`, {
        method: 'DELETE',
      });
      
      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.detail || 'Failed to delete task');
      }
      
      if (selectedTaskId === taskId) {
        selectedTaskId = null;
        activeTab = 'code';
        taskLogs = [];
        disconnectWebSocket();
      }
      
      fetchTasks();
      alert('Task deleted successfully');
    } catch (error) {
      console.error('Failed to delete task:', error);
      alert('Failed to delete task: ' + (error instanceof Error ? error.message : 'Unknown error'));
    }
  }

  function loadWriteToPV() {
    pythonCode = `import json
import os
from datetime import datetime

# Create results directory if it doesn't exist
results_dir = "/mnt/results"
os.makedirs(results_dir, exist_ok=True)

# Generate some data to save
task_id = os.getenv("ARGO_WORKFLOW_NAME", "unknown-task")
result_data = {
    "task_id": task_id,
    "timestamp": datetime.now().isoformat(),
    "status": "completed",
    "result": "Task executed successfully!",
    "data": {
        "processed_items": 42,
        "computation_time": 1.23,
        "output": "Sample output data"
    }
}

# Write to file
output_file = os.path.join(results_dir, f"{task_id}_result.json")
with open(output_file, "w") as f:
    json.dump(result_data, f, indent=2)

print(f"Results saved to {output_file}")
print(f"Data: {json.dumps(result_data, indent=2)}")`;
  }

  function loadReadFromPV() {
    pythonCode = `import json
import os
from datetime import datetime

# Read from results directory
results_dir = "/mnt/results"

if not os.path.exists(results_dir):
    print(f"Error: Results directory {results_dir} does not exist")
    exit(1)

# List all result files
result_files = [f for f in os.listdir(results_dir) if f.endswith("_result.json")]

if not result_files:
    print("No result files found in /mnt/results")
    print(f"Directory contents: {os.listdir(results_dir)}")
    exit(0)

print(f"Found {len(result_files)} result file(s):")
print("-" * 50)

# Read and display each result file
for result_file in sorted(result_files):
    file_path = os.path.join(results_dir, result_file)
    print(f"\\nReading: {result_file}")
    print("-" * 50)
    
    try:
        with open(file_path, "r") as f:
            data = json.load(f)
            print(json.dumps(data, indent=2))
    except Exception as e:
        print(f"Error reading {result_file}: {e}")

print("\\n" + "=" * 50)
print(f"Successfully read {len(result_files)} result file(s)")`;
  }

  onMount(() => {
    fetchTasks(true);
    
    // Set up periodic task status updates
    taskRefreshInterval = setInterval(() => {
      fetchTasks(false);
    }, TASK_REFRESH_INTERVAL_MS);
  });

  onDestroy(() => {
    disconnectWebSocket();
    if (taskRefreshInterval) {
      clearInterval(taskRefreshInterval);
      taskRefreshInterval = null;
    }
  });
</script>

<div class="container mx-auto p-8 max-w-7xl">
  <div class="flex justify-between items-center mb-8">
    <h1 class="text-3xl font-bold">Argo Workflow Manager</h1>
    <div class="flex gap-2">
      <Button 
        onclick={() => fetchTasks(true)} 
        disabled={initialLoading}
        variant="outline"
      >
        <RefreshCw size={20} class="mr-2" /> Refresh
      </Button>
      <Button 
        onclick={() => showSubmitModal = true}
        variant="default"
      >
        <Play size={20} class="mr-2" /> Run Python Task
      </Button>
    </div>
  </div>

  <div class="mt-8">
    <h2 class="text-2xl font-semibold mb-4">Submitted Tasks</h2>
    {#if initialLoading && tasks.length === 0}
      <p class="text-muted-foreground">Loading tasks...</p>
    {:else if tasks.length === 0}
      <p class="text-muted-foreground">No tasks found. Submit a task to get started.</p>
    {:else}
      <div class="rounded-md border mt-4">
        <table class="w-full border-collapse">
          <thead>
            <tr class="border-b">
              <th class="p-3 text-left font-medium">ID</th>
              <th class="p-3 text-left font-medium">Phase</th>
              <th class="p-3 text-left font-medium">Started</th>
              <th class="p-3 text-left font-medium">Finished</th>
              <th class="p-3 text-left font-medium">Created</th>
              <th class="p-3 text-left font-medium">Actions</th>
            </tr>
          </thead>
          <tbody>
            {#each tasks as task (task.id)}
              <TaskRow 
                {task}
                {getPhaseColor}
                onTaskClick={(t) => {
                  const newTaskId = t.id;
                  if (selectedTaskId !== newTaskId) {
                    selectedTaskId = newTaskId;
                    // Update previous values
                    prevSelectedTaskId = newTaskId;
                    // Clear logs when switching to a different task
                    taskLogs = [];
                    // Manually trigger WebSocket management
                    manageWebSocketConnection(newTaskId, activeTab);
                  }
                }}
                onCancel={cancelTask}
                onDelete={deleteTask}
              />
            {/each}
          </tbody>
        </table>
      </div>
    {/if}
  </div>

  {#if selectedTask}
    <TaskDialog
      task={selectedTask}
      {activeTab}
      setActiveTab={(tab) => {
        if (activeTab !== tab) {
          activeTab = tab;
          // Update previous values
          prevActiveTab = tab;
          // Manually trigger WebSocket management
          manageWebSocketConnection(selectedTaskId, tab);
        }
      }}
      {taskLogs}
      {loadingLogs}
      onClose={() => {
        selectedTaskId = null;
        activeTab = 'code';
        taskLogs = [];
        // Manually disconnect
        disconnectWebSocket();
        lastConnectedTaskId = null;
        lastConnectedTab = null;
      }}
      onCancel={cancelTask}
      onDelete={deleteTask}
    />
  {/if}

  <Dialog bind:open={showSubmitModal} class="max-w-4xl w-[90%] max-h-[85vh] overflow-auto flex flex-col">
    <div class="flex justify-between items-center mb-6">
      <h2 class="text-2xl font-semibold">Write Python Code to Execute</h2>
    </div>
    
    <div class="mb-4 flex gap-2 flex-wrap">
      <Button
        onclick={loadWriteToPV}
        disabled={submitting}
        variant="outline"
        size="sm"
      >
        📝 Load: Write to PV
      </Button>
      <Button
        onclick={loadReadFromPV}
        disabled={submitting}
        variant="outline"
        size="sm"
      >
        📖 Load: Read from PV
      </Button>
    </div>
    
    <div class="flex-1 min-h-[400px] mb-6">
      <MonacoEditor bind:value={pythonCode} language="python" theme="vs-dark" height="400px" />
    </div>

    <div class="flex gap-2 justify-end">
      <Button
        onclick={() => showSubmitModal = false}
        disabled={submitting}
        variant="outline"
      >
        Cancel
      </Button>
      <Button
        onclick={runTask}
        disabled={submitting || !pythonCode.trim()}
        variant="default"
      >
        {submitting ? 'Submitting...' : 'Submit Task'}
        {#if !submitting}
          <Play size={18} class="ml-2" />
        {/if}
      </Button>
    </div>
  </Dialog>
</div>

// apps/frontend/src/App.tsx
import React, { useState, useEffect } from 'react';
import { Play, RefreshCw, X } from 'lucide-react';
import Editor from '@monaco-editor/react';

interface Task {
  id: string;
  generateName: string;
  phase: string;
  startedAt: string;
  finishedAt: string;
  createdAt: string;
  pythonCode: string;
}

interface LogEntry {
  node: string;
  pod: string;
  phase: string;
  logs: string;
}

function App() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const [activeTab, setActiveTab] = useState<'code' | 'logs'>('code');
  const [taskLogs, setTaskLogs] = useState<LogEntry[]>([]);
  const [loadingLogs, setLoadingLogs] = useState(false);
  const [showSubmitModal, setShowSubmitModal] = useState(false);
  const [pythonCode, setPythonCode] = useState("print('Processing task in Kind...')");
  const [submitting, setSubmitting] = useState(false);
  const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:8000';

  const fetchTasks = async () => {
    try {
      setLoading(true);
      const res = await fetch(`${apiUrl}/api/v1/tasks`);
      const data = await res.json();
      setTasks(data.tasks || []);
    } catch (error) {
      console.error('Failed to fetch tasks:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTasks();
    // Refresh every 5 seconds
    const interval = setInterval(fetchTasks, 5000);
    return () => clearInterval(interval);
  }, []);

  const fetchTaskLogs = async (taskId: string) => {
    try {
      setLoadingLogs(true);
      const res = await fetch(`${apiUrl}/api/v1/tasks/${taskId}/logs`);
      if (!res.ok) {
        throw new Error('Failed to fetch logs');
      }
      const data = await res.json();
      setTaskLogs(data.logs || []);
    } catch (error) {
      console.error('Failed to fetch logs:', error);
      setTaskLogs([{
        node: 'error',
        pod: 'N/A',
        phase: 'Error',
        logs: `Error fetching logs: ${error instanceof Error ? error.message : 'Unknown error'}`
      }]);
    } finally {
      setLoadingLogs(false);
    }
  };

  useEffect(() => {
    if (selectedTask && activeTab === 'logs') {
      fetchTaskLogs(selectedTask.id);
      // Refresh logs every 3 seconds if task is still running
      const interval = setInterval(() => {
        if (selectedTask && (selectedTask.phase === 'Running' || selectedTask.phase === 'Pending')) {
          fetchTaskLogs(selectedTask.id);
        }
      }, 3000);
      return () => clearInterval(interval);
    }
  }, [selectedTask, activeTab]);

  const runTask = async () => {
    try {
      setSubmitting(true);
      const res = await fetch(`${apiUrl}/api/v1/tasks/submit`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ pythonCode }),
      });
      
      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.detail || 'Failed to submit task');
      }
      
      const data = await res.json();
      alert('Started Workflow: ' + data.id);
      setShowSubmitModal(false);
      // Refresh the task list
      fetchTasks();
    } catch (error) {
      console.error('Failed to submit task:', error);
      alert('Failed to submit task: ' + (error instanceof Error ? error.message : 'Unknown error'));
    } finally {
      setSubmitting(false);
    }
  };

  const getPhaseColor = (phase: string) => {
    switch (phase) {
      case 'Succeeded': return '#10b981';
      case 'Failed': return '#ef4444';
      case 'Running': return '#3b82f6';
      case 'Pending': return '#f59e0b';
      default: return '#6b7280';
    }
  };

  return (
    <div style={{ padding: '2rem', fontFamily: 'sans-serif', maxWidth: '1200px', margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <h1>Argo Workflow Manager</h1>
        <div style={{ display: 'flex', gap: '10px' }}>
          <button 
            onClick={fetchTasks} 
            disabled={loading}
            style={{ 
              display: 'flex', 
              gap: '8px', 
              padding: '10px 20px', 
              cursor: 'pointer',
              border: '1px solid #ccc',
              borderRadius: '4px',
              background: 'white'
            }}
          >
            <RefreshCw size={20} /> Refresh
          </button>
          <button 
            onClick={() => setShowSubmitModal(true)} 
            style={{ 
              display: 'flex', 
              gap: '8px', 
              padding: '10px 20px', 
              cursor: 'pointer',
              background: '#3b82f6',
              color: 'white',
              border: 'none',
              borderRadius: '4px'
            }}
          >
            <Play size={20} /> Run Python Task
          </button>
        </div>
      </div>

      <div style={{ marginTop: '2rem' }}>
        <h2>Submitted Tasks</h2>
        {loading && tasks.length === 0 ? (
          <p>Loading tasks...</p>
        ) : tasks.length === 0 ? (
          <p>No tasks found. Submit a task to get started.</p>
        ) : (
          <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '1rem' }}>
            <thead>
              <tr style={{ borderBottom: '2px solid #e5e7eb', textAlign: 'left' }}>
                <th style={{ padding: '12px' }}>ID</th>
                <th style={{ padding: '12px' }}>Phase</th>
                <th style={{ padding: '12px' }}>Started</th>
                <th style={{ padding: '12px' }}>Finished</th>
                <th style={{ padding: '12px' }}>Created</th>
              </tr>
            </thead>
            <tbody>
              {tasks.map((task) => (
                <tr 
                  key={task.id} 
                  style={{ 
                    borderBottom: '1px solid #e5e7eb',
                    cursor: 'pointer',
                    transition: 'background-color 0.2s'
                  }}
                  onClick={() => setSelectedTask(task)}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.backgroundColor = '#f9fafb';
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.backgroundColor = 'transparent';
                  }}
                >
                  <td style={{ padding: '12px', fontFamily: 'monospace' }}>{task.id}</td>
                  <td style={{ padding: '12px' }}>
                    <span style={{
                      padding: '4px 8px',
                      borderRadius: '4px',
                      background: getPhaseColor(task.phase),
                      color: 'white',
                      fontSize: '12px',
                      fontWeight: 'bold'
                    }}>
                      {task.phase || 'Unknown'}
                    </span>
                  </td>
                  <td style={{ padding: '12px' }}>
                    {task.startedAt ? new Date(task.startedAt).toLocaleString() : '-'}
                  </td>
                  <td style={{ padding: '12px' }}>
                    {task.finishedAt ? new Date(task.finishedAt).toLocaleString() : '-'}
                  </td>
                  <td style={{ padding: '12px' }}>
                    {task.createdAt ? new Date(task.createdAt).toLocaleString() : '-'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* Modal for displaying Python code */}
      {selectedTask && (
        <div 
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000
          }}
          onClick={() => setSelectedTask(null)}
        >
          <div 
            style={{
              backgroundColor: 'white',
              borderRadius: '8px',
              padding: '2rem',
              maxWidth: '800px',
              width: '90%',
              maxHeight: '80vh',
              overflow: 'auto',
              boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)'
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
              <h2 style={{ margin: 0 }}>Task Details - {selectedTask.id}</h2>
              <button
                onClick={() => {
                  setSelectedTask(null);
                  setActiveTab('code');
                  setTaskLogs([]);
                }}
                style={{
                  background: 'none',
                  border: 'none',
                  fontSize: '24px',
                  cursor: 'pointer',
                  color: '#6b7280',
                  padding: '0',
                  width: '30px',
                  height: '30px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center'
                }}
              >
                ×
              </button>
            </div>
            <div style={{ marginBottom: '1rem', display: 'flex', gap: '10px', alignItems: 'center' }}>
              <span style={{
                padding: '4px 8px',
                borderRadius: '4px',
                background: getPhaseColor(selectedTask.phase),
                color: 'white',
                fontSize: '12px',
                fontWeight: 'bold'
              }}>
                {selectedTask.phase || 'Unknown'}
              </span>
            </div>
            
            {/* Tabs */}
            <div style={{ display: 'flex', borderBottom: '1px solid #e5e7eb', marginBottom: '1rem' }}>
              <button
                onClick={() => setActiveTab('code')}
                style={{
                  padding: '10px 20px',
                  border: 'none',
                  background: 'none',
                  cursor: 'pointer',
                  borderBottom: activeTab === 'code' ? '2px solid #3b82f6' : '2px solid transparent',
                  color: activeTab === 'code' ? '#3b82f6' : '#6b7280',
                  fontWeight: activeTab === 'code' ? 'bold' : 'normal'
                }}
              >
                Code
              </button>
              <button
                onClick={() => setActiveTab('logs')}
                style={{
                  padding: '10px 20px',
                  border: 'none',
                  background: 'none',
                  cursor: 'pointer',
                  borderBottom: activeTab === 'logs' ? '2px solid #3b82f6' : '2px solid transparent',
                  color: activeTab === 'logs' ? '#3b82f6' : '#6b7280',
                  fontWeight: activeTab === 'logs' ? 'bold' : 'normal'
                }}
              >
                Logs {loadingLogs && '...'}
              </button>
            </div>

            {/* Tab Content */}
            {activeTab === 'code' ? (
              <div style={{
                backgroundColor: '#1e1e1e',
                color: '#d4d4d4',
                padding: '1rem',
                borderRadius: '4px',
                fontFamily: 'monospace',
                fontSize: '14px',
                whiteSpace: 'pre-wrap',
                overflow: 'auto',
                border: '1px solid #3e3e3e',
                maxHeight: '60vh'
              }}>
                {selectedTask.pythonCode || 'No Python code available'}
              </div>
            ) : (
              <div style={{
                backgroundColor: '#1e1e1e',
                color: '#d4d4d4',
                padding: '1rem',
                borderRadius: '4px',
                fontFamily: 'monospace',
                fontSize: '14px',
                whiteSpace: 'pre-wrap',
                overflow: 'auto',
                border: '1px solid #3e3e3e',
                maxHeight: '60vh'
              }}>
                {loadingLogs ? (
                  <div style={{ color: '#9ca3af' }}>Loading logs...</div>
                ) : taskLogs.length === 0 ? (
                  <div style={{ color: '#9ca3af' }}>No logs available yet. The task may still be starting.</div>
                ) : (
                  taskLogs.map((logEntry, index) => (
                    <div key={index} style={{ marginBottom: '1.5rem' }}>
                      <div style={{ 
                        color: '#60a5fa', 
                        marginBottom: '0.5rem',
                        paddingBottom: '0.5rem',
                        borderBottom: '1px solid #374151'
                      }}>
                        <strong>Pod:</strong> {logEntry.pod} | <strong>Node:</strong> {logEntry.node} | <strong>Phase:</strong> {logEntry.phase}
                      </div>
                      <div style={{ 
                        color: '#d4d4d4',
                        whiteSpace: 'pre-wrap',
                        wordBreak: 'break-word'
                      }}>
                        {logEntry.logs}
                      </div>
                    </div>
                  ))
                )}
              </div>
            )}
          </div>
        </div>
      )}

      {/* Modal for submitting new task with code editor */}
      {showSubmitModal && (
        <div 
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1001
          }}
          onClick={() => !submitting && setShowSubmitModal(false)}
        >
          <div 
            style={{
              backgroundColor: 'white',
              borderRadius: '8px',
              padding: '2rem',
              maxWidth: '900px',
              width: '90%',
              maxHeight: '85vh',
              overflow: 'auto',
              boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
              display: 'flex',
              flexDirection: 'column'
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
              <h2 style={{ margin: 0 }}>Write Python Code to Execute</h2>
              <button
                onClick={() => !submitting && setShowSubmitModal(false)}
                disabled={submitting}
                style={{
                  background: 'none',
                  border: 'none',
                  cursor: submitting ? 'not-allowed' : 'pointer',
                  color: '#6b7280',
                  padding: '0',
                  width: '30px',
                  height: '30px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  opacity: submitting ? 0.5 : 1
                }}
              >
                <X size={24} />
              </button>
            </div>
            
            <div style={{ marginBottom: '1rem', display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
              <button
                onClick={() => setPythonCode(`import json
import os
from datetime import datetime

# Create results directory if it doesn't exist
results_dir = "/mnt/results"
os.makedirs(results_dir, exist_ok=True)

# Generate some data to save
task_id = os.getenv("ARGO_WORKFLOW_NAME", "unknown-task")
result_data = {
    "task_id": task_id,
    "timestamp": datetime.now().isoformat(),
    "status": "completed",
    "result": "Task executed successfully!",
    "data": {
        "processed_items": 42,
        "computation_time": 1.23,
        "output": "Sample output data"
    }
}

# Write to file
output_file = os.path.join(results_dir, f"{task_id}_result.json")
with open(output_file, "w") as f:
    json.dump(result_data, f, indent=2)

print(f"Results saved to {output_file}")
print(f"Data: {json.dumps(result_data, indent=2)}")`)}
                disabled={submitting}
                style={{
                  padding: '8px 16px',
                  cursor: submitting ? 'not-allowed' : 'pointer',
                  border: '1px solid #3b82f6',
                  borderRadius: '4px',
                  background: 'white',
                  color: '#3b82f6',
                  fontSize: '14px',
                  opacity: submitting ? 0.5 : 1
                }}
              >
                📝 Load: Write to PV
              </button>
              <button
                onClick={() => setPythonCode(`import json
import os
from datetime import datetime

# Read from results directory
results_dir = "/mnt/results"

if not os.path.exists(results_dir):
    print(f"Error: Results directory {results_dir} does not exist")
    exit(1)

# List all result files
result_files = [f for f in os.listdir(results_dir) if f.endswith("_result.json")]

if not result_files:
    print("No result files found in /mnt/results")
    print(f"Directory contents: {os.listdir(results_dir)}")
    exit(0)

print(f"Found {len(result_files)} result file(s):")
print("-" * 50)

# Read and display each result file
for result_file in sorted(result_files):
    file_path = os.path.join(results_dir, result_file)
    print(f"\\nReading: {result_file}")
    print("-" * 50)
    
    try:
        with open(file_path, "r") as f:
            data = json.load(f)
            print(json.dumps(data, indent=2))
    except Exception as e:
        print(f"Error reading {result_file}: {e}")

print("\\n" + "=" * 50)
print(f"Successfully read {len(result_files)} result file(s)")`)}
                disabled={submitting}
                style={{
                  padding: '8px 16px',
                  cursor: submitting ? 'not-allowed' : 'pointer',
                  border: '1px solid #10b981',
                  borderRadius: '4px',
                  background: 'white',
                  color: '#10b981',
                  fontSize: '14px',
                  opacity: submitting ? 0.5 : 1
                }}
              >
                📖 Load: Read from PV
              </button>
            </div>
            
            <div style={{ 
              flex: 1,
              minHeight: '400px',
              border: '1px solid #e5e7eb',
              borderRadius: '4px',
              overflow: 'hidden',
              marginBottom: '1.5rem'
            }}>
              <Editor
                height="400px"
                defaultLanguage="python"
                value={pythonCode}
                onChange={(value) => setPythonCode(value || '')}
                theme="vs-dark"
                options={{
                  minimap: { enabled: false },
                  fontSize: 14,
                  lineNumbers: 'on',
                  scrollBeyondLastLine: false,
                  automaticLayout: true,
                }}
              />
            </div>

            <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
              <button
                onClick={() => setShowSubmitModal(false)}
                disabled={submitting}
                style={{
                  padding: '10px 20px',
                  cursor: submitting ? 'not-allowed' : 'pointer',
                  border: '1px solid #ccc',
                  borderRadius: '4px',
                  background: 'white',
                  opacity: submitting ? 0.5 : 1
                }}
              >
                Cancel
              </button>
              <button
                onClick={runTask}
                disabled={submitting || !pythonCode.trim()}
                style={{
                  padding: '10px 20px',
                  cursor: (submitting || !pythonCode.trim()) ? 'not-allowed' : 'pointer',
                  border: 'none',
                  borderRadius: '4px',
                  background: '#3b82f6',
                  color: 'white',
                  opacity: (submitting || !pythonCode.trim()) ? 0.5 : 1,
                  display: 'flex',
                  gap: '8px',
                  alignItems: 'center'
                }}
              >
                {submitting ? 'Submitting...' : (
                  <>
                    <Play size={18} /> Submit Task
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
